services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/backend/laravel
    volumes:
      - ./backend/laravel:/var/www/backend/laravel/
    environment:
      XDEBUG_MODE: "off"
      PHP_OPCACHE_ENABLE: 1
    depends_on:
      - db
    networks: [app]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/laravel:/var/www/backend/laravel/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/admin.conf:/etc/nginx/conf.d/admin.conf
      - ./frontend/vue/dist:/var/www/frontend/dist/
    depends_on:
      - php
    networks: [app]

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks: [app]

  db:
    image: mysql:8.0
    container_name: mysql_corp
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks: [app]

networks:
  app:
    driver: bridge
volumes:
  mysql-data: